---
- name: Demo around Nxos DME feature
  hosts: dme_nxos
  gather_facts: false
  tasks:
    - name: Do some interface configuration with DME endpoints
      cisco.dme_nxos.dme_nxos_interfaces:
        config:
          - name: Ethernet1/1
            enabled: true
          - name: Ethernet1/2
            description: Configured by Ansible test
            enabled: true
            speed: auto
            mode: Layer2
            mtu: 1500
            snmp:
              trap:
                link_status: true
        state: merged
      register: result_gathered

    - name: Config validation on box with direct configuration
      cisco.dme_nxos.dme_nxos_config_dirty:
        lines:
          - description A really long description for this demo
          - no speed 10000
          - duplex full
          - mtu 4096
          - ip forward
        parents: interface Ethernet1/2

    - name: Config validation on box with direct configuration, multiple failure
      cisco.dme_nxos.dme_nxos_config_dirty:
        lines:
          - switchport
          - switchport mode trunk
          - switchport trunk allowed vlan 1001-1200
          - spanning-tree port type edge trunk
          - spannisng-tree bpdufilter enable
          - lacp vpc-convergence
          - vpc 10
        parents: interface port-channel10

    - name: Config validation on box, handling device defaults
      cisco.dme_nxos.dme_nxos_config_dirty:
        lines:
          - no description as it was a bad description
          - no speed 100000
          - duplex full
          - mtu 4096
        parents: interface Ethernet1/2

    - name: Config validation on box, an invalid configuration
      cisco.dme_nxos.dme_nxos_config_dirty:
        lines:
          - Adescription A wrong spelling for description
          - speed 100000
          - duplex full
          - mtu 4096
        parents: interface Ethernet1/2
