# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# ansible.content_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the documentation in the module file and re-run
# ansible.content_builder commenting out
# the path to external 'docstring' in build.yaml.
#
##############################################

"""
The arg spec for the dme_nxos_config_validate module
"""


class Config_validateArgs(object):  # pylint: disable=R0903
    """The arg spec for the dme_nxos_config_validate module
    """

    argument_spec = {
        "lines": {"type": "list", "aliases": ["commands"], "elements": "str"},
        "parents": {"type": "list", "elements": "str"},
        "src": {"type": "path"},
        "replace_src": {"type": "str"},
        "before": {"type": "list", "elements": "str"},
        "after": {"type": "list", "elements": "str"},
    }  # pylint: disable=C0301
