---
name: Release

on: # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    with:
      environment: galaxy
    secrets:
      ah_token: ${{ secrets.GALAXY_TOKEN }}